// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID          uuid.UUID
	FeederID    uuid.UUID
	Title       string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Feeder struct {
	ID        uuid.UUID
	Name      string
	Link      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
