// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createFeeder = `-- name: CreateFeeder :one
insert into
    feeders (id, name, link)
values ($1, $2, $3)
returning
    id, name, link, created_at, updated_at
`

type CreateFeederParams struct {
	ID   uuid.UUID
	Name string
	Link string
}

func (q *Queries) CreateFeeder(ctx context.Context, arg CreateFeederParams) (Feeder, error) {
	row := q.db.QueryRowContext(ctx, createFeeder, arg.ID, arg.Name, arg.Link)
	var i Feeder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Link,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
